configuration:
  window-size:
    width: 1024
    height: 600
  group-pages: true
dimensions:
  - name: "A/4"
    size:
      width: 210
      height: 297
  - name: "A/3"
    size:
      width: 297
      height: 420
  - name: "A/5"
    size:
      width: 148
      height: 210
  - name: "A/6"
    size:
      width: 105
      height: 148
  - name: "Letter"
    size:
      width: 216
      height: 279
  - name: "A/2"
    size:
      width: 420
      height: 594
  - name: "A/1"
    size:
      width: 594
      height: 841
  - name: "A/0"
    size:
      width: 841
      height: 1189
  - name: "B/4"
    size:
      width: 250
      height: 353
  - name: "B/3"
    size:
      width: 353
      height: 500
  - name: "B/2"
    size:
      width: 500
      height: 707

filters:
#  - text: "Select A/3-as"
#    rules:
#      - min-short-side: 217
#        max-short-side: 297
#        min-long-side: 217
#        max-long-side: 420
#      - min-short-side: 0
#        max-short-side: 297
#        min-long-side: 298
#        max-long-side: 420

language: HU

dictionaries:
  - name: HU
    words:
    - id: open-pdf
      value: "PDF megnyitása"
    - id: page-count
      value: "Darab"
    - id: dimensions
      value: "Méret"
    - id: short
      value: "Rövid"
    - id: long
      value: "Hosszú"
    - id: paper-size
      value: "Szabvány"
    - id: pages
      value: "Oldalak"
    - id: surface-text
      value: "Kiválasztott oldalak teljes felülete"
    - id: filter-action
      value: "Szűrés módja"
    - id: filter-select-rows
      value: "Kiválasztás"
    - id: filter-change-bg-color
      value: "Háttérszín változtatás"
    - id: unknown
      value: "ismeretlen"
  - name: EN
    words:
    - id: open-pdf
      value: "Open PDF"
    - id: page-count
      value: "Page count"
    - id: dimensions
      value: "Dimensions"
    - id: short
      value: "Short"
    - id: long
      value: "Long"
    - id: paper-size
      value: "Paper size"
    - id: pages
      value: "Pages"
    - id: surface-text
      value: "The surface of selected pages"
    - id: filter-action
      value: "Filter action"
    - id: filter-select-rows
      value: "Select rows"
    - id: filter-change-bg-color
      value: "Change background color"
    - id: unknown
      value: "unknown"
